### ISSUE TITLE
Missing/Invalid claim "kid" in auth header

### ISSUE THREAD

**Issue by reyco1** [PhantomAppDevelopment/todo-app#2]
Getting this error when trying to save a todo item... Any ideas what it could be refering to? All my google searches lead me to using something called JWT (http://fabricemontfort.com/firebase-and-as3-ep-2-login-with-oauth-2-0/).

I appreciate the help!

**Comment by agentphantom** [comment]
This means you are sending the idToken as the auth parameter.

You must send the access_token from a Refresh Token request as the auth parameter.

Later this week, I will update this app to reflect these changes.

**Comment by reyco1** [comment]
Got it working... Thanks!
